/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TesteWebhookRouteImport } from './routes/teste-webhook'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PreCadastroRouteImport } from './routes/pre-cadastro'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppReimbursementsRouteImport } from './routes/_app.reimbursements'
import { Route as AppPolicyRouteImport } from './routes/_app.policy'
import { Route as AppOverviewRouteImport } from './routes/_app.overview'
import { Route as AppExpensesIndexRouteImport } from './routes/_app.expenses.index'
import { Route as ApiPublicReimbursementsRouteImport } from './routes/api/public/reimbursements'
import { Route as AppExpensesIdRouteImport } from './routes/_app.expenses.$id'

const TesteWebhookRoute = TesteWebhookRouteImport.update({
  id: '/teste-webhook',
  path: '/teste-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PreCadastroRoute = PreCadastroRouteImport.update({
  id: '/pre-cadastro',
  path: '/pre-cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppReimbursementsRoute = AppReimbursementsRouteImport.update({
  id: '/reimbursements',
  path: '/reimbursements',
  getParentRoute: () => AppRoute,
} as any)
const AppPolicyRoute = AppPolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesIndexRoute = AppExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicReimbursementsRoute = ApiPublicReimbursementsRouteImport.update({
  id: '/api/public/reimbursements',
  path: '/api/public/reimbursements',
  getParentRoute: () => rootRouteImport,
} as any)
const AppExpensesIdRoute = AppExpensesIdRouteImport.update({
  id: '/expenses/$id',
  path: '/expenses/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pre-cadastro': typeof PreCadastroRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teste-webhook': typeof TesteWebhookRoute
  '/overview': typeof AppOverviewRoute
  '/policy': typeof AppPolicyRoute
  '/reimbursements': typeof AppReimbursementsRoute
  '/reports': typeof AppReportsRoute
  '/users': typeof AppUsersRoute
  '/expenses/$id': typeof AppExpensesIdRoute
  '/api/public/reimbursements': typeof ApiPublicReimbursementsRoute
  '/expenses/': typeof AppExpensesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pre-cadastro': typeof PreCadastroRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teste-webhook': typeof TesteWebhookRoute
  '/overview': typeof AppOverviewRoute
  '/policy': typeof AppPolicyRoute
  '/reimbursements': typeof AppReimbursementsRoute
  '/reports': typeof AppReportsRoute
  '/users': typeof AppUsersRoute
  '/expenses/$id': typeof AppExpensesIdRoute
  '/api/public/reimbursements': typeof ApiPublicReimbursementsRoute
  '/expenses': typeof AppExpensesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pre-cadastro': typeof PreCadastroRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teste-webhook': typeof TesteWebhookRoute
  '/_app/overview': typeof AppOverviewRoute
  '/_app/policy': typeof AppPolicyRoute
  '/_app/reimbursements': typeof AppReimbursementsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/expenses/$id': typeof AppExpensesIdRoute
  '/api/public/reimbursements': typeof ApiPublicReimbursementsRoute
  '/_app/expenses/': typeof AppExpensesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/pre-cadastro'
    | '/signup'
    | '/sitemap.xml'
    | '/teste-webhook'
    | '/overview'
    | '/policy'
    | '/reimbursements'
    | '/reports'
    | '/users'
    | '/expenses/$id'
    | '/api/public/reimbursements'
    | '/expenses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/pre-cadastro'
    | '/signup'
    | '/sitemap.xml'
    | '/teste-webhook'
    | '/overview'
    | '/policy'
    | '/reimbursements'
    | '/reports'
    | '/users'
    | '/expenses/$id'
    | '/api/public/reimbursements'
    | '/expenses'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/pre-cadastro'
    | '/signup'
    | '/sitemap.xml'
    | '/teste-webhook'
    | '/_app/overview'
    | '/_app/policy'
    | '/_app/reimbursements'
    | '/_app/reports'
    | '/_app/users'
    | '/_app/expenses/$id'
    | '/api/public/reimbursements'
    | '/_app/expenses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PreCadastroRoute: typeof PreCadastroRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TesteWebhookRoute: typeof TesteWebhookRoute
  ApiPublicReimbursementsRoute: typeof ApiPublicReimbursementsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teste-webhook': {
      id: '/teste-webhook'
      path: '/teste-webhook'
      fullPath: '/teste-webhook'
      preLoaderRoute: typeof TesteWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-cadastro': {
      id: '/pre-cadastro'
      path: '/pre-cadastro'
      fullPath: '/pre-cadastro'
      preLoaderRoute: typeof PreCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reimbursements': {
      id: '/_app/reimbursements'
      path: '/reimbursements'
      fullPath: '/reimbursements'
      preLoaderRoute: typeof AppReimbursementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/policy': {
      id: '/_app/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof AppPolicyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses/': {
      id: '/_app/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof AppExpensesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/reimbursements': {
      id: '/api/public/reimbursements'
      path: '/api/public/reimbursements'
      fullPath: '/api/public/reimbursements'
      preLoaderRoute: typeof ApiPublicReimbursementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/expenses/$id': {
      id: '/_app/expenses/$id'
      path: '/expenses/$id'
      fullPath: '/expenses/$id'
      preLoaderRoute: typeof AppExpensesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppOverviewRoute: typeof AppOverviewRoute
  AppPolicyRoute: typeof AppPolicyRoute
  AppReimbursementsRoute: typeof AppReimbursementsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppExpensesIdRoute: typeof AppExpensesIdRoute
  AppExpensesIndexRoute: typeof AppExpensesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppOverviewRoute: AppOverviewRoute,
  AppPolicyRoute: AppPolicyRoute,
  AppReimbursementsRoute: AppReimbursementsRoute,
  AppReportsRoute: AppReportsRoute,
  AppUsersRoute: AppUsersRoute,
  AppExpensesIdRoute: AppExpensesIdRoute,
  AppExpensesIndexRoute: AppExpensesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PreCadastroRoute: PreCadastroRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TesteWebhookRoute: TesteWebhookRoute,
  ApiPublicReimbursementsRoute: ApiPublicReimbursementsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
