CREATE TABLE public.despesas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  telefone TEXT,
  recibo TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

GRANT SELECT ON public.despesas TO authenticated;
GRANT ALL ON public.despesas TO service_role;

ALTER TABLE public.despesas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated employees can view despesas"
  ON public.despesas
  FOR SELECT
  TO authenticated
  USING (true);

ALTER TABLE public.despesas REPLICA IDENTITY FULL;
ALTER PUBLICATION supabase_realtime ADD TABLE public.despesas;